"""simplify model

Revision ID: d4a37eb50b99
Revises: cc0ce4e84dc9
Create Date: 2025-01-17 15:30:46.055708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a37eb50b99'
down_revision = 'cc0ce4e84dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Beer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_Beer_name'), ['name'], unique=False)
        batch_op.drop_constraint('Beer_style_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Style', ['style_id'], ['id'])
        batch_op.drop_column('style')

    with op.batch_alter_table('Brewery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Brewery_name'), ['name'], unique=False)

    with op.batch_alter_table('Style', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Style', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('Brewery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Brewery_name'))

    with op.batch_alter_table('Beer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Beer_style_fkey', 'Style', ['style'], ['id'])
        batch_op.drop_index(batch_op.f('ix_Beer_name'))
        batch_op.drop_column('style_id')

    # ### end Alembic commands ###
